#define TAM_ALUNO 3
#define TAM_PROFESSOR 3
#define TAM_DISCIPLINA 5


#define CAD_ALUNO_SUCESSO -1
#define MATRICULA_INVALIDA -2
#define LISTA_CHEIA -3
#define ATUALIZACAO_ALUNO_SUCESSO -4
#define MATRICULA_INEXISTENTE -5
#define EXCLUSAO_SUCESSO -6

#define CAD_PROFESSOR_SUCESSO -7
#define ATUALIZACAO_PROFESSOR_SUCESSO -8

#define COD_DISCIPLINA_SUCESSO -9

#define SEXO_INVALIDO -10

#endif